### ISSUE TITLE
command prompt not working

### ISSUE THREAD

**Issue by ghost** [zachng1/cutup#1]
Trying to test out the code as I am curious about the cut up technique but even though I have the control.py and text.py file, the command prompts you have provided in the readme don't seem to work? Keep getting an invalid syntax error in the command line? any help? tried without quotations also

![Screenshot 2021-08-02 at 20 40 32](https://user-images.githubusercontent.com/83061116/127914600-90590443-c090-4ce6-a247-53197f4bc386.png)

**Comment by zachng1** [comment]
Would you be able to copy paste the entire error? The screen shot you've shared cuts off a bit early for me to read the whole thing.

Although it looks like you may be running the file *inside* the python interpreter. Try running it on the normal bash or cmd command line *with* python3 instead. `$ python3 control.py etc. `

**Comment by ghost** [comment]
> Would you be able to copy paste the entire error? The screen shot you've shared cuts off a bit early for me to read the whole thing.
> 
> Although it looks like you may be running the file _inside_ the python interpreter. Try running it on the normal bash or cmd command line _with_ python3 instead. `$ python3 control.py etc.`

Sorry for late reply been fairly busy. Won’t be able to get that error message to you today but I have some time tomorrow so I’ll defo get back to you then. Thanks for the reply, still really interested to see how this code works!

**Comment by ghost** [comment]
Hello again, I think I have got the program to work, but I think I am doing something wrong in regards to the outputted text. I have two poems in docx style but when I use them it only outputs one line of text? Just wondering if you can give me some guidance on what kind of text you use and if you have an example at hand? First 2 screenshots are the two poems and the last screenshot is the output.

![Screenshot 2021-08-07 at 11 08 31](https://user-images.githubusercontent.com/83061116/128596856-bd10c79d-836e-466f-a53f-62d3d74c0be6.png)

------------------------------------------------------------------------------------------------

![Screenshot 2021-08-07 at 11 10 42](https://user-images.githubusercontent.com/83061116/128596859-1d82ddab-5c2e-4c03-9ce1-069ef53bc7ee.png)

------------------------------------------------------------------------------------------------

![Screenshot 2021-08-07 at 11 11 22](https://user-images.githubusercontent.com/83061116/128596864-4bf47cc0-36d7-40f2-be10-bb23f76cf76c.png)

**Comment by zachng1** [comment]
Yeah, this is definitely quite an old project of mine and it had more than its fair share of bugs. Would you mind sending me the two poem files and letting me know the exact options you are using ? I'll have a look and see if i can figure out what the issue is

**Comment by ghost** [comment]
Yeah sure I'll get them to you. in terms of the options I'm choosing, I'm just using:

control.py -c5 poem1.docx poem2.docx output.docx

[poem1.docx](https://github.com/zachng1/cutup/files/6954858/poem1.docx)


[poem2.docx](https://github.com/zachng1/cutup/files/6954859/poem2.docx)

**Comment by zachng1** [comment]
Try pull the latest changes, i should have fixed it now. Let me know if you have any other issues :)

**Comment by ghost** [comment]
Cool, thanks for the swift help! I’ll have a look at the changes tomorrow and see how it runs and get back to you with feedback! 👍

**Comment by ghost** [comment]
Hello again, been trying to access the .py files but for some reason it just will not allow me to have permission? 

![Screenshot 2021-08-10 at 21 52 45](https://user-images.githubusercontent.com/83061116/128933566-0778683f-1f01-4b71-9ec1-1c31b3d06c7f.png)

Tried everything on my end, is there a chance you could check the privileges of the python files? Not sure why it is all of a sudden showing a permission denied error, didn't have this issue before. Thanks!

**Comment by ghost** [comment]
I did a quick check of the permissions and I have permissions to read and write but not to execute which is weird? not sure if that is helpful.

**Comment by zachng1** [comment]
Hmm that's strange. Try `chmod +x control.py` etc. Although if running them
with the interpreter you should only need read access 🤔🤔

**Comment by ghost** [comment]
Got it working for the most part. The issue is that if there are paragraphs it will only cut up or fold in the first paragraph. If I used just a one paragraph piece of text then it will carry out the techniques just fine. 

Quick question, if you don't mind, could I just ask what your thinking was to create the control.py file for the UI? Is It entirely possible to just use the text.py file and copy the paths into that file somewhere then run the file and it will carry out the cut up or fold in techniques then save the output? So just a one file solution if you are not interested in the audio or video segments? Great job by the way, it is fun to see what new literature the program outputs and some outputs have been rather funny to read :)

**Comment by zachng1** [comment]
Hmmm not easily - you could try copying lines 36-42 from the control.py
file into the top of the text one, and then setting all the relevant
variables manually? Will probably require a bit of trouble shooting to get
working though. The point of separating the control file from the text one
was yeah, essentially so it's easy to trigger text, audio, or video cut ups
from the same place.

Would you mind giving me an example of when it has only used the first
paragraph? That sounds like something I'd like to fix

**Comment by ghost** [comment]
hello again do apologise for the very late reply but in response to your question yeah there seems to be an issue with poems with paragraphs. With the two below poems:

[poem1.docx](https://github.com/zachng1/cutup/files/7063984/poem1.docx)


[poem2.docx](https://github.com/zachng1/cutup/files/7063985/poem2.docx)

using both the cut up method and the fold in method only produces a 1 paragraph output? It is very strange, maybe you will have better luck with what's going on? This is what the code spits out as the output: 

![Screenshot 2021-08-27 at 04 34 44](https://user-images.githubusercontent.com/83061116/131068188-7a16d945-7a39-4c22-b899-b21cad942cf2.png)

**Comment by zachng1** [comment]
give it a shot now. if you're interested it was an issue with the python `split()` method cutting out newline characters as well as whitespaces.

**Comment by ghost** [comment]
Interesting, yes, in terms of poetry there is now more of a structure present. There is one last issue that I've noticed and it is to do with the cut up method. I've been looking at some short stories and running it through your code to see what kind of new stories are outputted and the issue I've noticed is that short stories never end with a full stop? but the fold in method in the code usually always finishes with a full stop? 

For example:

Text 1:

[A Blanket Decision.docx](https://github.com/zachng1/cutup/files/7072153/A.Blanket.Decision.docx)

text 2:

[The Audubon Bar.docx](https://github.com/zachng1/cutup/files/7072154/The.Audubon.Bar.docx)

output:

![Screenshot 2021-08-29 at 09 39 06](https://user-images.githubusercontent.com/83061116/131244287-0fa96ced-2353-43ec-a1e2-ef3f1aaf4120.png)

Might be something looking into? Could very well improve the prose of the outputted text?

**Comment by zachng1** [comment]
Ah yep that will be because the fold in alternates I sections between your
two stories so will always have a full stop as long as one of your stories
ends in a full stop, I.e. the final words will be the final words from one
of the stories.

At the minute cut up just jumbles everything about including punctuation. I
think I'll probably leave that as is though since it's quite trivial to add
the full stop afterward.
